# Generated by Django 5.0 on 2023-12-19 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('publication_date', models.DateField()),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('extracted_text', models.TextField(null=True)),
                ('document', models.FileField(upload_to='documents/newspapers')),
                ('processing_status', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('page_number', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='newspapers/extracted_images')),
                ('associated_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document')),
            ],
        ),
    ]
